# Nearest Neighbor Classifier
I coded up this part following Lecture 2 of the course. 

In [2]:
import numpy as np

# L1 distance
Also called 'Manhattan distance'

In [ ]:
class NearestNeighbor:
    def __init__(self):
        pass
    # train function: memorize training data
    def train(self, X, y):
        # X is an NxD matrix, where each row is an example. There are N rows
        self.Xtr = X
        # y is an N-tuple
            # ith entry in y = label for ith example in x
        self.Ytr = y
    
    def predict(self, X):
        """ extract N, aka number of test e.g.s"""
        # X is our new data. It's NxD mtx
        # for each row i (aka ith training e.g.) in X, we want label
        N = X.shape[0]
        # make input and output the SAME type
        Ypred = np.zeros(N, dtype = self.ytr.dtype)
        # iterate over test rows!
        for i in range(N):
            # we got example i
            # tldr: for ea pt Xi in X, find Xtr_i, Closest-to-Xi point in Xtr
            # X[i,:] SLICES matrix X, dim = (D,1)
                # we get row i, remove All otr rows
                # axis = 1 means sum by Rows (axis = 0 sums columns)
                # so self.Xtr - X[i,:] means:
                # subtract vector X[i,:] from ALL Rows of matrix
                # so in following code, we get arr of N sums
                # -> this ONLY work bc, D match up in NxD and Dx1
            distances = np.sum(np.abs(self.Xtr - X[i,:]), axis = 1)
            # get index for image M with smallest distance
                # np.argmin(arr) returns INDEX of Smallest entry in array arr
            min_idx = np.argmin(distances)
            # label of ith 
            Ypred[i] = self.ytr[min_idx]
        return Ypred

In [9]:
# How does the np.sum() thing work?
X = np.array([
    [1, 1, 1],
    [4, 5, 6]
])
print(X.shape)
print(X[1,:]) # extract entire row of X by index
print(X - X[1,:]) # subtract All rows in X by row X[1,:]
print(np.sum((X - X[1,:]), axis = 1)) # sum input matrix by ROWs

(2, 3)
[4 5 6]
[[-3 -4 -5]
 [ 0  0  0]]
[-12   0]


# Analysis
Run time:
>train() takes $O(1)$ time
><br>predict() takes $O(N)$ time

It's OK that we train() slowly
>BUT, we want **FAST** predict()
><br>because that's when we actually USE the model!